matrix:
  include:
  - language: python

    python:
    - "3.6"

    install:
    - python tridentweb/setup.py install
    - pip install coverage

    script:
    - cd tridentweb
    - nosetests -v --with-coverage --cover-package=tridentweb

    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - language: java
    dist: trusty
    sudo: required

    jdk:
    - openjdk11

    cache:
      directories:
      - $HOME/.gradle/caches
      - $HOME/.gradle/wrapper

    before_install:
    - chmod +x gradlew

    install:
      ./gradlew --configure-on-demand :api:assemble --console=plain

    script:
      ./gradlew --configure-on-demand :api:check --console=plain

    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

    after_success:
    - if [ -e ./gradlew ]; then ./gradlew --configure-on-demand :api:jacocoTestReport; else gradle :api:jacocoTestReport; fi
    - bash <(curl -s https://codecov.io/bash)

  - language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28

      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

    cache:
      directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache

    before_install:
    - chmod +x gradlew
    - openssl aes-256-cbc -K $encrypted_aeae3d0f88e6_key -iv $encrypted_aeae3d0f88e6_iv -in ./clock/google-services.json.enc -out ./clock/google-services.json -d

    install:
      ./gradlew --configure-on-demand :clock:clean --console=plain

    script:
      ./gradlew --configure-on-demand :clock:testDebugUnitTest --console=plain

    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

    after_success:
    - if [ -e ./gradlew ]; then ./gradlew --configure-on-demand :clock:testDebugUnitTestCoverage; else gradle :clock:testDebugUnitTestCoverage; fi
    - bash <(curl -s https://codecov.io/bash) -f 'test*.xml'

