matrix:
  include:
    - language: java
      dist: trusty
      sudo: required

      jdk:
        - openjdk11

      cache:
        directories:
          - $HOME/.gradle/caches
          - $HOME/.gradle/wrapper

      before_install:
        - chmod +x gradlew

      install:
        ./gradlew --configure-on-demand :api:assemble --console=plain

      script:
        ./gradlew --configure-on-demand :api:check --console=plain

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      after_success:
        - if [ -e ./gradlew ]; then ./gradlew --configure-on-demand :api:jacocoTestReport; else gradle jacocoTestReport; fi
        - bash <(curl -s https://codecov.io/bash)

    - language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28

        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache

      before_install:
        - chmod +x gradlew

      install:
        ./gradlew --configure-on-demand :clock:assemble --console=plain

      script:
        ./gradlew --configure-on-demand :clock:build :clock:connectedCheck --console=plain

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      after_success:
        - if [ -e ./gradlew ]; then ./gradlew --configure-on-demand :clock:jacocoTestReport; else gradle jacocoTestReport; fi
        - bash <(curl -s https://codecov.io/bash)