name: Orbit Viewer CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orbit-viewer
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Setup
        run: npm ci
        
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
